language: rust
sudo: false
cache: cargo
rust:
  - stable
before_script:
  - (mdbook -V | grep -qi "^mdbook\s*v0\.2" || cargo install mdbook --version "^0.2" --force)
script:
- mdbook build
- (git clone https://github.com/rust-random/rand.git && cd rand && cargo build && cd .. && mdbook test -L rand/target/debug/deps)

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local-dir: book
  keep-history: false
  on:
    branch: master
