name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with: 
            mdbook-version: 'latest'

      - name: Setup mdbook-theme latest
        run: |
          curl -s https://api.github.com/repos/zjp-CN/mdbook-theme/releases/latest \
               | grep browser_download_url \
               | grep mdbook-theme_linux \
               | cut -d '"' -f 4 \
               | wget -qi -
          tar -xvzf mdbook-theme_linux.tar.gz
          echo $PWD >> $GITHUB_PATH

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./book
